name: gymnastic_center
description: "Your new companion for fitness and health."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cached_video_player: ^2.0.4
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.1
  flutter_native_splash: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_vector_icons: ^2.0.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  pinput: ^4.0.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-launcher/app_icon.png"
  adaptive_icon_background: "assets/app-launcher/app_launcher_icon_background.png"
  image_path_ios: "assets/app-launcher/app_launcher_icon.png"

flutter_native_splash:
  background_image: "assets/splash_background.png"
  image: assets/logo_color.png
  android_12:
    color: "#ffffff"
  image_ios: assets/logo_white_large.png
flutter:
  uses-material-design: true

  fonts:
    - family: GymnasticCenter
      fonts:
        - asset: fonts/GymnasticCenter.ttf

  assets:
    - assets/
    - .env
