name: flutter_template
description: 'A new Flutter project.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.0.1
  google_fonts: ^6.2.1
  pinput: ^4.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
