name: gymnastic_center
description: 'Your new companion for fitness and health.'
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  avatar_glow: ^3.0.1
  cached_video_player:
    git:
      url: https://github.com/vikram25897/flutter_cached_video_player
      ref: feature/gradle_version_bump
  cupertino_icons: ^1.0.6
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: ^17.0.1
  flutter_native_splash: ^2.4.0
  flutter_secure_storage: ^9.1.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_vector_icons: ^2.0.0
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: ^0.19.0
  pinput: ^4.0.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  timeago: ^3.6.1

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: '^0.13.1'
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/app-launcher/launcher-icon.png'
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  background_image: 'assets/splash_background.png'
  image: assets/logo_white_large.png

  android_12:
    color: '#ffffff'

  image_ios: assets/logo_white_large.png

flutter:
  uses-material-design: true

  fonts:
    - family: GymnasticCenter
      fonts:
        - asset: fonts/GymnasticCenter.ttf

  assets:
    - assets/
    - assets/plan-setup/
    - assets/location/
    - assets/onboarding/
    - assets/app-launcher/
    - .env
